### ISSUE TITLE
Related Tools in Academic Advising

### ISSUE THREAD

**Issue by SultanEid** [SultanEid/GP1-G3-AcademicAdviser#10]
You should do a background check on any other tool that has done similar system to yours. Then you can state your contributions/differences or the advance in the state of the art.

a table with properties or features provided by at least 3-4 other systems

**Comment by SultanEid** [comment]
Please update this issue with tour latest progress before the end of Sunday.

**Comment by Moha2001-dev** [comment]
The final Related Tools in Academic Advising report

[Related_Tools_in_Academic_Advising.pdf](https://github.com/SultanEid/GP1-G3-AcademicAdviser/files/9543326/Related_Tools_in_Academic_Advising.pdf)

**Comment by Moha2001-dev** [comment]
Add Scheduling Feature and remove the appointment scheduling feature.
[Related_Tools_in_Academic_Advising.pdf](https://github.com/SultanEid/GP1-G3-AcademicAdviser/files/9591618/Related_Tools_in_Academic_Advising.pdf)
