### ISSUE TITLE
Process Model

### ISSUE THREAD

**Issue by SultanEid** [SultanEid/GP1-G3-AcademicAdviser#11]
Please update this issue with the process model we have discussed in our first meeting. Note that the incremental model is the most suitable for your type of project considering team size and the contiuous integration plan.

**Comment by Moha2001-dev** [comment]
![Group 11](https://user-images.githubusercontent.com/80723154/190855779-917bda7b-c666-47db-a1ea-e2e54298ef95.png)

**Comment by Moha2001-dev** [comment]
![Group 38](https://user-images.githubusercontent.com/80723154/194775386-abe4ea2b-2334-41b6-9861-bc18a65f66f3.png)
