### ISSUE TITLE
Writing problem summary

### ISSUE THREAD

**Issue by SultanEid** [SultanEid/GP1-G3-AcademicAdviser#2]
Write a summary about the project idea and why this project is important. In addition, mention the issues academic advisers face when dealing with student and how this system can help them.

**Comment by YamenAlrehaili** [comment]
https://taibahuniv-my.sharepoint.com/:w:/g/personal/tu4000688_taibahu_edu_sa/ET2gxr7hUPtEqFOTZhMZrt8BD46w8NSeS_tZM4oQhS2Fzw?e=3buiuo
