### ISSUE TITLE
Requirements Engineering

### ISSUE THREAD

**Issue by SultanEid** [SultanEid/GP1-G3-AcademicAdviser#3]
The goal is to have a draft of the requirements.

Functional
Non-Functional Requirements

**Comment by AmMosnhi** [comment]
i have finished the non-functional requirement textually in the report and also on piStar.



![Image](https://user-images.githubusercontent.com/108613469/196059765-a28ff058-02fb-4a26-a136-6a2f3f0bb598.png)



[goalModel (3).txt](https://github.com/SultanEid/GP1-G3-AcademicAdviser/files/9795748/goalModel.3.txt)
