### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by SultanEid** [SultanEid/GP1-G3-AcademicAdviser#4]
Weite use cases

- texually including flow of events
- Graphically using UML Use Case

**Comment by AmMosnhi** [comment]
![Image](https://user-images.githubusercontent.com/108613469/188597841-e52204d2-8eed-4d21-be08-bd4f18fcad1d.jpeg)

**Comment by AmMosnhi** [comment]
Graphically using UML Use Case:

![Image](https://user-images.githubusercontent.com/108613469/193427911-85885c44-e0dd-47e0-8c59-533b6c3d860f.png)

**Comment by AmMosnhi** [comment]
Update on UML Use Case to meet our latest requirement.
 

![Image](https://user-images.githubusercontent.com/108613469/195214073-160d0b5c-505f-40c0-b38b-122589457336.jpg)


Still working on "textually including flow of events"

**Comment by AmMosnhi** [comment]
I've updated Use Case to meet our latest requirement.

![Image](https://user-images.githubusercontent.com/108613469/196059990-50c8ba57-0823-4911-9e5b-80dcf08e3d92.jpg)

**Comment by AmMosnhi** [comment]
last update on Use case:

![Image](https://user-images.githubusercontent.com/108613469/196899504-1f3bb383-f063-4365-a37c-c54e65c64104.jpg)

use case description:

[usecase description Complete(Updated 20.10).docx](https://github.com/SultanEid/GP1-G3-AcademicAdviser/files/9827953/usecase.description.Complete.Updated.20.10.docx)
