### ISSUE TITLE
Student Profile UI

### ISSUE THREAD

**Issue by SultanEid** [SultanEid/GP1-G3-AcademicAdviser#41]
Implementing Student Profile UI

**Comment by Moha2001-dev** [comment]
Done

![Image](https://user-images.githubusercontent.com/80723154/212532444-eeb9607d-9ce3-46dd-ad2a-b4adfeae59a9.png)

**Comment by Moha2001-dev** [comment]
update


![Image](https://user-images.githubusercontent.com/80723154/212540029-8847941f-28f4-4dd7-bcf3-d93e9a2dad8a.png)

**Comment by SultanEid** [comment]
Possibility to enhance this feature by adding student plan, will be marked as closed for now.

**Comment by Moha2001-dev** [comment]
@Moha2001-dev , @YamenAlrehaili  and @AmMosnhi  are Designing Student Plan page would you have any comments or suggestions on the design or the structure?
https://user-images.githubusercontent.com/80723154/214113074-7dd1670d-fe4a-4f13-b651-048f1f22b032.mp4
