### ISSUE TITLE
Academic Advisor UI Report

### ISSUE THREAD

**Issue by YamenAlrehaili** [SultanEid/GP1-G3-AcademicAdviser#50]
Implementing UI Report, and It's Backend from saving a  number of selected widgets and use those widget to create a pdf and download the pdf.

**Comment by Moha2001-dev** [comment]
Done UI and pdf generation:
![image](https://user-images.githubusercontent.com/80723154/211229098-22d506c8-7779-40d6-9e6f-1044bdd20e9c.png)

**Comment by Moha2001-dev** [comment]
Generated Sample:
[out11 (25).pdf](https://github.com/SultanEid/GP1-G3-AcademicAdviser/files/10369924/out11.25.pdf)

**Comment by SultanEid** [comment]
update: 

1. add report generating buttons

**Comment by SultanEid** [comment]
- [ ] Fix Checkboxes for Adviser page
- [ ] Addd report generating button at the button fo the page with green colour.

**Comment by Moha2001-dev** [comment]
@Moha2001-dev  , @YamenAlrehaili and @AmMosnhi  fixed the bug

**Comment by Moha2001-dev** [comment]
@Moha2001-dev , @YamenAlrehaili and @AmMosnhi redesign the print button and add home button

![Image](https://user-images.githubusercontent.com/80723154/214118194-a31f8538-d0c6-4f55-9b76-88d8f0c41b51.png)
