### ISSUE TITLE
Student Scores UI

### ISSUE THREAD

**Issue by Moha2001-dev** [SultanEid/GP1-G3-AcademicAdviser#57]
Implementing Student Scores UI

**Comment by Moha2001-dev** [comment]
to be modify 


![Image](https://user-images.githubusercontent.com/80723154/212839106-0499089b-9f8a-4d02-82e4-901eccda311d.png)

**Comment by SultanEid** [comment]
- [ ] Page gap in the middle - needs to be fixed 
- [ ] A column to show the student's grades for each course
