### ISSUE TITLE
Student Report UI

### ISSUE THREAD

**Issue by Moha2001-dev** [SultanEid/GP1-G3-AcademicAdviser#58]
Implementing Student Report UI

**Comment by Moha2001-dev** [comment]
Done}


![Image](https://user-images.githubusercontent.com/80723154/212836500-af5bfdbb-6805-4c35-9750-46400a0cd28f.png)

**Comment by SultanEid** [comment]
Things to be updated:

1. Check boxes not working check issue
2. update report generation button (Green)

**Comment by SultanEid** [comment]
Also update #50

**Comment by Moha2001-dev** [comment]
@Moha2001-dev  , @YamenAlrehaili and @AmMosnhi  fixed the bug

**Comment by Moha2001-dev** [comment]
@Moha2001-dev , @YamenAlrehaili and @AmMosnhi redesign the print button and add home button

![Image](https://user-images.githubusercontent.com/80723154/214118194-a31f8538-d0c6-4f55-9b76-88d8f0c41b51.png)
