### ISSUE TITLE
Survey on Academic Advising 

### ISSUE THREAD

**Issue by SultanEid** [SultanEid/GP1-G3-AcademicAdviser#7]
Please write what you can regarding your research method on deciding what is essential in the academic advising system, particularly the following points:
- What data is to be included in the report for the academic adviser
- what data to be included for the student view
- What does the academic adviser expect to see in the report to make him make a better decision.
- Is there any repeated process than can be useful if automated during the academic advising period?

In addition, you should discuss the method you have used to answer these questions:
- who are the participants? regular academic adviser? head of the academic advising committee? Vice-dean of academic affair ? head of department?
- How did you collect the answer ? interview? Questionaire ? was your method setup online or papers handed in person ?
- what is your idea regarding the analysis of the collected information?
- Any tables you are trying to fill ?

What is the process?
1- Contacting the participant
2- sending a link with the questionnaire explaining the idea behind it.
3- assisting the participant by explaining any question that wasn't clear ??
.... and and ...

What are you hoping to achieve from collecting these answers ?

**Comment by YamenAlrehaili** [comment]
https://docs.google.com/forms/d/1bq1rZqTKUPSYQotxNKWjobKBcaN2c7FkSkOnbEse2iY/edit?usp=sharing

**Comment by YamenAlrehaili** [comment]
The last version of the survey 
https://forms.gle/fEXf5ECgwCgFYKri8

**Comment by Moha2001-dev** [comment]
![QR Code](https://user-images.githubusercontent.com/80723154/190441676-a204ec9b-9548-4881-8e2f-956c819fb3f3.png)
